services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    entrypoint: sh .docker/entrypoint.sh
    container_name: import_csv
    working_dir: /app
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app